// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg3WnYRlvuwmYvD9xkSiAy6hMclloQ4Tk',
    appId: '1:326681056399:android:616f6d599b8717bdd08cfa',
    messagingSenderId: '326681056399',
    projectId: 'flutterfirecustomauth',
    storageBucket: 'flutterfirecustomauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tS1wS8tOQppeCwqQzrUV7McEUdk0p68',
    appId: '1:326681056399:ios:335b3375bba7f6bad08cfa',
    messagingSenderId: '326681056399',
    projectId: 'flutterfirecustomauth',
    storageBucket: 'flutterfirecustomauth.appspot.com',
    androidClientId: '326681056399-76cd9huc6pkl8cgoqpvq4ki04h5ffboj.apps.googleusercontent.com',
    iosClientId: '326681056399-fbc3qmigu8i0g7p4juq6e2ou5aui6m28.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestAuthentication',
  );
}
